### ISSUE TITLE
File system metrics using Pure-fa-opemmetrics-exporter

### ISSUE THREAD

**Issue by s-kuchi** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#80]
Does the exporter export file system metrics from Pure flasharray?

**Comment by sdodsley** [comment]
Yes - there is an endpoint `/directories` that provides directory/filesystem performance and capacity information,

We are still updating our documentation for this, but these are the metrics provided...

| Metric Name                                  | Metric key                                   | Description                                  | Units       |
| -------------------------------------------- | -------------------------------------------- | -------------------------------------------- | ----------- |
| PureFA Directory Performance Average Bytes   | purefa_directory_performance_average_bytes   | FlashArray directory average operations size | Byte        |
| PureFA Directory Performance Bandwidth Bytes | purefa_directory_performance_bandwidth_bytes | FlashArray directory bandwidth               | Byte        |
| PureFA Directory Performance Throughput Iops | purefa_directory_performance_throughput_iops | FlashArray directory throughput              | Count       |
| PureFA Directory Performance Latency Usec    | purefa_directory_performance_latency_usec    | FlashArray directory latency                 | MicroSecond |
| PureFA Directory Space Bytes                 | purefa_directory_space_bytes                 | FlashArray directory space in bytes          | Byte        |
| PureFA Directory Space Data Reduction Ratio  | purefa_directory_space_data_reduction_ratio  | FlashArray directory space data reduction    | Unspecified |

**Comment by s-kuchi** [comment]
Hi @sdodsley : I don't see purefa_directory_* metrics in Prometheus.

Following is the version of exporter we are running.

REPOSITORY                                                   TAG         IMAGE ID      CREATED      SIZE
quay.io/purestorage/pure-fa-om-exporter  latest      13228d136231  3 weeks ago  22.2 MB

![image](https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/assets/133256656/08660888-2168-4d4e-a848-d363b330cc04)

**Comment by sdodsley** [comment]
@s-kuchi they should definatley be there. We released v1.0.9, with the `latest` tag applied 14 days ago. Please ensure you are using that image.

**Comment by james-laing** [comment]
@s-kuchi check the config and targets to ensure the scrapes are successful.

### Check the Exporter
To ensure the exporter is providing scraped data, perform a cURL command to ensure you get the results.
```
curl -k -H 'Authorization: Bearer xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' -X GET 'https://exporteraddress:9490/metrics/directories?endpoint=array01.fqdn.com'
```
### Check Prometheus
1. Status > Configuration (ensure your config file contains the endpoint to `/metrics/directories`)
2. Status > Targets (depending on the version of Prometheus you may need to clear filters to show all targets)
    Find the target for `/metrics/directories`. If it is red it will show the error.

**Comment by s-kuchi** [comment]
Thank you @sdodsley and @james-laing .
I upgraded to the latest image and modified the yml file to include /metrics/directories. When I run the curl command, i get the following output. I still don't see purefa_directories in prometheus. The array doesn't currently have any directories created. I will test it again once it has and post the output. Let me know from the below output, if it is working as expected.

```
[root@pduulpprmpol01 prometheus]# curl -k -H 'Authorization: Bearer xxx' -X GET 'http://pduulpprmpol01.corp.siriusxm.com:9490/metrics/directories?endpoint=10.21.188.35'
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0.000158391
go_gc_duration_seconds{quantile="0.25"} 0.00020494
go_gc_duration_seconds{quantile="0.5"} 0.000225141
go_gc_duration_seconds{quantile="0.75"} 0.000250931
go_gc_duration_seconds{quantile="1"} 0.000407802
go_gc_duration_seconds_sum 66.890000495
go_gc_duration_seconds_count 286127
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 1090
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.21.0"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 3.3397648e+07
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 5.711688905024e+12
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 4317
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 6.8146866065e+10
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 6.306168e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 3.3397648e+07
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 4.0706048e+07
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 4.4818432e+07
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 206024
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 3.2964608e+07
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 8.552448e+07
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.6939213758183472e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 6.8147072089e+10
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 76800
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 78000
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 1.1382e+06
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 1.564416e+06
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 4.431e+07
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 1.0817051e+07
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 1.0944512e+07
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 1.0944512e+07
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 1.15238944e+08
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 66
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 91876.26
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 575
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 8.6499328e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.69341765535e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.34723584e+09
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes 1.8446744073709552e+19
# HELP purefa_info FlashArray system information
# TYPE purefa_info gauge
purefa_info{array_name="ddc-dev-pure-c60",os="Purity//FA",system_id="c9cee10b-70a6-4f05-9a79-3f1eec15052e",version="6.4.9"} 1
```

**Comment by james-laing** [comment]
@s-kuchi it's odd to have returned `purefa_info` but none of the directory metrics.

Please can you run the following and provide us with the output:
```
docker images --digests
```

**Comment by s-kuchi** [comment]
@james-laing 
```
[root@pduulpprmpol01 zapi]# docker images --digests
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
REPOSITORY                               TAG         DIGEST                                                                   IMAGE ID      CREATED      SIZE
quay.io/purestorage/pure-fa-om-exporter  latest      sha256:4024923a2032fd689705f09a11022b8f562247f8ae0d5a4bbf52a92c800d0d00  e697ad66d954  2 weeks ago  22.3 MB
<none>                                   <none>      sha256:1fc69f0889bbe6272538665fc9fb281f822e021136c1d983f54b165cb2ff12f5  13228d136231  4 weeks ago  22.2 MB
```

**Comment by sdodsley** [comment]
@s-kuchi i think because you don't have any directories created that is why you are seeing no datapoints. Create a directory and try again
